{% set name = "hesperos" %}
{% set version = "0.1.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hesperos-{{ version }}.tar.gz
  sha256: eee6e2c7fe07030b10859f87b15804a842441c536390e4a9581cf0722b53511a
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - imageio-ffmpeg
    - napari <0.4.15
    - napari-plugin-engine
    - numpy
    - pandas
    - python >=3.8
    - qtpy
    - scikit-image
    - scikit-learn
    - simpleitk
    - tifffile

test:
  imports:
    - hesperos
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chgodard/hesperos
  summary: A plugin to manually or semi-automatically segment medical data and correct previous segmentation data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
