{% set name = "hesperos" %}
{% set version = "0.1.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hesperos-{{ version }}.tar.gz
  sha256: c53801685aec75548e771c38697262cd15d4b4dd967eaad79778d79158d155a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - imageio-ffmpeg
    - napari <0.4.15
    - napari-plugin-engine
    - numpy
    - pandas
    - python >=3.8
    - qtpy
    - scikit-image
    - scikit-learn
    - scipy
    - simpleitk
    - tifffile

test:
  imports:
    - hesperos
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chgodard/hesperos
  summary: A plugin to manually or semi-automatically segment medical data and correct previous segmentation data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
